-- init.sql

CREATE SCHEMA geo_app AUTHORIZATION user_1;

GRANT ALL PRIVILEGES ON SCHEMA geo_app TO user_1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA geo_app TO user_1;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA geo_app TO user_1;