openapi: 3.0.0
info:
  title: Distance Calculation Service API
  version: 1.0.0
  description: API для расчета расстояний между адресами и возврата результатов.
servers:
  - url: http://localhost:5000/

paths:
  /api/calculateDistances:
    post:
      summary: Load CSV file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                  message:
                    type: string
        '400':
          description: Data validation error

  /api/getResult/{result_id}:
    get:
      summary: Getting results
      parameters:
        - name: result_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  task_id:
                    type: string
                  data:
                    type: object
                    description: List of address points
                    items:
                      type: string
                    links:
                      type: object
                      additionalProperties:
                        type: number
                        description: Value associated with the link
        '404':
          description: Not found
